### ISSUE TITLE
To Xianming, things you need to do.

### ISSUE THREAD

**Issue by YuhangSong** [YuhangSong2017/grl#10]
@XianmingWang 

1. Write your models.

2. Set up DATASET, DOMAIN, GRID_SIZE as google doc requires (see https://github.com/YuhangSong/grl/issues/9). Just conduct the experiment with your name in it.

3. Test your model and plot the result with (https://github.com/YuhangSong/grl/issues/8).

4. Fill the result in the google doc. Use the result at 10K iteration. The yellow line is filtered to be the mean value of recent 50 plots, so you can just refer to the value on the yellow line.

**Comment by XianmingWang** [comment]
guo ran zhe yang qing chu duo le, me me da
